### ISSUE TITLE
Unable to use jnetpcap in Tomcat

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#1]
The jnetpcap uses libpcap.so. If I use jnetpcap in Eclipse, everything works fine. But, when ported to Tomcat, the application crashes with failed JNI link to libpcap.so.

**Comment by prasadtalasila** [comment]
A few pointers to solution.

http://stackoverflow.com/questions/6150428/native-libraries-not-found-in-tomcat?lq=1
http://wiki.apache.org/tomcat/HowTo#I.27m_encountering_classloader_problems_when_using_JNI_under_Tomcat
http://stackoverflow.com/questions/16185200/jna-java-lang-unsatisfiedlinkerror-and-the-specified-module-could-not-be-found?rq=1

**Comment by prasadtalasila** [comment]
Integration of jnetpcap into the project after the first alpha release on Feb 20th, 2016.

**Comment by crygnus** [comment]
Just for the sake of recent findings about integrating jnetPcap with Tomcat refer to [this wiki](https://github.com/prasadtalasila/PacketAnalyzer/wiki/jnetPcap)

**Comment by crygnus** [comment]
Do we still need to keep this issue open? I don't see any roadmap to use jnetPcap in our application. Is it still on the plate?

**Comment by prasadtalasila** [comment]
We can close this for now.
