### ISSUE TITLE
Local server with continuous logged in state in Cyberoam

### ISSUE THREAD

**Issue by crygnus** [prasadtalasila/BITS-Darshini#10]
A server with better configuration than that set up (link is [here](https://github.com/prasadtalasila/PacketAnalyzer/issues/5)) is needed. Computer center at the college can provide such a server but it needs to be continuously logged into cyberoam client.

**Comment by prasadtalasila** [comment]
Because of potential for abuse, continuously logged / authenticated server is undesirable. The cyberoam Linux client can be used as and when a need for Internet connection is desirable.

The pending work is to update the OS libraries for letting the Cyberoam Linux clients to login.

**Comment by prasadtalasila** [comment]
The work is done. Now users can access Internet by using Cyberoam clients on the local server.
