### ISSUE TITLE
Wiki for application front-end development

### ISSUE THREAD

**Issue by crygnus** [prasadtalasila/BITS-Darshini#11]
Please provide wiki pages describing work done, plans for future work, design diagrams and discussions with the instructor for the benefit of other contributors. When the relevant wiki pages are created then feel free to close this issue.

Also if possible add the goals to the [Project Timeline](https://github.com/prasadtalasila/PacketAnalyzer/wiki/Project-Timeline) page and weekly tasks to [Weekly Work Schedule](https://github.com/prasadtalasila/PacketAnalyzer/wiki/Weekly-Work-Schedule) page.

**Comment by crygnus** [comment]
Should this be closed???
I see this wiki page - https://github.com/prasadtalasila/PacketAnalyzer/wiki/Front-End-Design  
AND  
this timline/schedule page - https://github.com/prasadtalasila/PacketAnalyzer/wiki/UI-Weekly-Schedule

If this is sufficient then close the issue.

**Comment by prasadtalasila** [comment]
Sukanto needs to add the backbone MVC framework information on the https://github.com/prasadtalasila/PacketAnalyzer/wiki/Front-End-Design or a new wiki page.

**Comment by prasadtalasila** [comment]
The front end was completely redone by Sebastin Santy. We can close this issue.
