### ISSUE TITLE
Jenkins integration

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#12]
The Jenkins on AWS VM needs to be integrated with GitHub repo to provide the following features.
1) Webhook integration with GitHub
2) Build status on main page of the repo.

Refs:
http://stackoverflow.com/questions/14274293/show-current-state-of-jenkins-build-on-github-repo
http://stackoverflow.com/questions/13546097/how-do-show-my-tests-passing-failing-in-github

**Comment by prasadtalasila** [comment]
The given Jenkins tutorial doc has been helpful in settiup the Jenkins instance and in integrating the first war file. The build succeeds, but the deployment does not take place.

The final war file should have been copied to Tomcat apps/ directory with the right configuration files. This last step does not happen.

**Comment by prasadtalasila** [comment]
The Jenkins setup tutorial has been helpful in setting up an CI environment on the local server. Jenkins successfully integrates, but can't deploy the war automatically. The console output for both the build runs is available on the local server.

There is a need for clarity on the latter steps.

**Comment by crygnus** [comment]
As far as setting up Jenkins is concerned, the tutorial provides correct information. The issue with deploying WAR file was the issue with Tomcat setup. For updated deployment document please refer to the latest report submitted. Closing the issue now. Feel free to reopen the issue if it is still not clear.
