### ISSUE TITLE
Remove nodesource_setup.sh after node setup is complete

### ISSUE THREAD

**Issue by SebastinSanty** [prasadtalasila/BITS-Darshini#124]
Either remove `nodesource_setup.sh` after node setup is complete or change the download directory, as putting in the working directory of darshini, makes it appear in git changes.

Check [this](https://github.com/prasadtalasila/BITS-Darshini/blob/dev/scripts/install.sh#L43)

**Comment by prasadtalasila** [comment]
fixed in #128.
