### ISSUE TITLE
Change of ElasticSearch port

### ISSUE THREAD

**Issue by SebastinSanty** [prasadtalasila/BITS-Darshini#125]
Why was the ElasticSearch port (vagrant exposed) changed? My local app regressed due to this change. Am I missing anything? I reverted back to port 9200, the app is working fine for me.

Check [this](https://github.com/prasadtalasila/BITS-Darshini/blob/master/Vagrantfile#L9)

**Comment by prasadtalasila** [comment]
ES port changed to 9200 in all code locations in 65c3344. No improvement in functionality.
