### ISSUE TITLE
Move all data structure defining logic to backend

### ISSUE THREAD

**Issue by SebastinSanty** [prasadtalasila/BITS-Darshini#126]
At present, backend does only a half job of making `_source` key with id, experimentName, description, experimenter, pcapPath attributes. `collaborators` attribute is added after this initial object is made. There can be problems arising due to network errors in future.

As we can see that there is no benefit of adding collaborator attribute from the front-end (it was done during rapid development), it is suggested to add such an attribute from backend, even though it is an empty field, so as to keep up with the consistency.

**Comment by prasadtalasila** [comment]
Not a priority right now.
