### ISSUE TITLE
Exception in Session termination

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#138]
When an experiment is run using Experiment.java class, the concurrent protocol analysis is launched by Session.java. Sometimes the experiment concludes successfully. Sometimes, one of the threads in the threadpool throws up the following error.
```
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at in.ac.bits.protocolanalyzer.persistence.repository.SaveRepository.run(SaveRepository.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The exception is always on line-113 of SaveRepository.java. Surprisingly enough, the unit test on Experiment.java passes successfully.

Completing the following work would help illuminate the problem better
1. Collect corroborating information from SaveRepository.java
1. Create a unit test, preferably on SaveRepository.java that always triggers this error.

**Comment by prasadtalasila** [comment]
Such NullPointerExceptions occur in other places too, for example in TransportAnalyzer.java, EventBus$LoggingHandler.java and AnalyzerCell.java.

The central problem seems to be that of incorrect termination of a multi-threaded protocol analysis session. If we reduce the threadpool size to one, then all errors disappear; but, then the protocol analysis becomes sequential. Hence, we do need the threadpool size to be more than one.

**Comment by prasadtalasila** [comment]
Debugging ideas.

1. Use Stop VM option for all break points in order to check the state of all the threads in the application. Please see this [stackoverflow](https://stackoverflow.com/questions/5375538/debugging-multiple-threads-in-eclipse) issue for a way of doing so.    
1. Identify the threads that consistently throw up exceptions. Giving names to threads might make the job easier.

**Comment by prasadtalasila** [comment]
@adityaketkar I have a hunch that we might have setup the ExperimentTest.java incorrectly. For the research paper results, I have repeatedly run the experiments from command-line. Some of these tests are in [darshini-test.sh](https://github.com/prasadtalasila/BITS-Darshini/blob/dev/scripts/measurements/darshini-test.sh) file. Can you run this file and see the log files?

I remember seeing the results being same for repeated runs. This means that the execution of the project in Tomcat happens correctly, but not outside of the tomcat. We might need to investigate the reason for the same.

**Comment by adityaketkar** [comment]
@prasadtalasila I named the threads using ThreadFactoryBuilder().
So far, most of the NullPointerExceptions seem to be coming from [here](https://github.com/prasadtalasila/BITS-Darshini/blob/66389118069d170974596642e2ab6c9abebafd8b/src/main/java/in/ac/bits/protocolanalyzer/analyzer/transport/TransportAnalyzer.java#L40).
Please have a look at the screenshot below.
![image](https://user-images.githubusercontent.com/22611315/35431519-c658ebe8-02a2-11e8-8a8a-d6f8de9c6426.png)

**Comment by adityaketkar** [comment]
@prasadtalasila I tried to backtrack the null PacketWrapper issue, and I think the following is the breaking point : 

![image](https://user-images.githubusercontent.com/22611315/35433446-75c1c716-02a9-11e8-884e-e84e319788bf.png)

Here is the console log of the print statements It's clear that the packet inserted into the queue is never null, but when popping a PacketWrapper out of the queue, some of them become null somehow .
[Test_Log.txt](https://github.com/prasadtalasila/BITS-Darshini/files/1667285/Test_Log.txt)

**Comment by prasadtalasila** [comment]
PR #161 solves the issue.
