### ISSUE TITLE
Configuration information in deployment

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#14]
How to persist the configuration information from development to deployment and by pass Git repo.

**Comment by prasadtalasila** [comment]
Seems like fairly straightforward solution. The appropriate references to the solution are:

http://stackoverflow.com/questions/13956651/externalizing-tomcat-webapp-config-from-war-file
http://tomcat.apache.org/tomcat-7.0-doc/config/context.html

The lesson is that Context xml file of the Web application defined in $CATALINA_HOME/myHost/myApp.xml should contain path to properties file.

**Comment by crygnus** [comment]
We do have such a file in place ($CATALINA_HOME/conf/Catalina/localhost/protocolanalyzer.xml) which contains following for now - 

`<?xml version="1.0" encoding="UTF-8"?>
<Context antiJARLocking="false" docBase="/path/to/protocolanalyzer/target/protocolanalyzer-1.0-SNAPSHOT" path="/protocolanalyzer"/>`

(Actually antiJARLocking was set to true initially and I made it false to resolve library reloading problem tracked in [this issue](https://github.com/prasadtalasila/PacketAnalyzer/issues/6)).

Are you suggesting that we will separately deploy this file with the package which will have information like credentials and so on?

**Comment by prasadtalasila** [comment]
The context xml file can have environment variables set. One type of the environment variables set is a properties filename. Once this properties file name with its' path is set, the Tomcat web application can load credentials from this file.

Another type of the environment variables we can set is the directory for pcap files. Right now, we are assuming this directory to be a fixed location. This directory location can also be set as an environment variable.

**Comment by crygnus** [comment]
Please refer to the final report submitted where it is delineated that if the application is loaded via Tomcat HTML/script manager then such [context path is already present in the application](https://github.com/prasadtalasila/PacketAnalyzer/blob/backend/src/main/webapp/META-INF/context.xml).

The context file described in the previous comment is necessary when Tomcat is run via directly running catalina.sh script.
