### ISSUE TITLE
code profiling

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#146]
The BITS Darshini code needs to be profiled to identify the memory and throughput bottlenecks. We are interested in classes and packages that are problem candidates so that we can improve them.

**Comment by ParvDani07** [comment]
[BottleNeck1.zip](https://github.com/prasadtalasila/BITS-Darshini/files/1612576/BottleNeck1.zip)
This is a snapshot of a session recording. To view bottlenecks, please go to CPU Views -> Hot Spots

**Comment by prasadtalasila** [comment]
@ParvDani07 please update the [code profile](https://github.com/prasadtalasila/BITS-Darshini/wiki/Code-Profile) page with the relevant information.

**Comment by prasadtalasila** [comment]
Some work done for now. More to be continued later.
