### ISSUE TITLE
Spring handling of bean and component creation in a package

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#173]

**Comment by prasadtalasila** [comment]
The corresponding [wiki page](https://github.com/prasadtalasila/BITS-Darshini/wiki/CT-Component) shall be updated by @kapilkalra04.

**Comment by prasadtalasila** [comment]
@kapilkalra04 is this work complete?

**Comment by kapilkalra04** [comment]
Yes and the concerned wiki pages explaining the two are :
[CT Component](https://github.com/prasadtalasila/BITS-Darshini/wiki/CT-Component)
[CT Bean](https://github.com/prasadtalasila/BITS-Darshini/wiki/CT-Bean)
