### ISSUE TITLE
All packets read from pcap file are held in memory

### ISSUE THREAD

**Issue by crygnus** [prasadtalasila/BITS-Darshini#18]
Currently packets extracted from pcap file are processed very **inefficiently**. All the packets are extracted at once and stored in the memory (in the form of a list). This list is bounced around from one layer analyzer to next. This approach would not work for pcap files with very large number of packets.

Pipeline implementation must be provided to parse and process the packet one at a time.

**Comment by prasadtalasila** [comment]
The pom.xml file shows a lot of dependencies that we may not be using now. Removing unnecessary loads may reduce the memory footprint of the application.

**Comment by crygnus** [comment]
PcapFileReader class has been modified and [here is the new readFile](https://github.com/prasadtalasila/PacketAnalyzer/blob/backend/src/main/java/com/bits/protocolanalyzer/input/PcapFileReader.java#L44) method. Handling packets this way reduces memory requirement. Live monitoring on aws server (using bash htop) indicated **more than 150 MB** of less memory usage than previous version of application.

**Comment by crygnus** [comment]
Moreover, for any file, application would not hold all the read packets from pcap file into memory. This way application is equipped to handle pcap files of any size.

**Comment by prasadtalasila** [comment]
Good. BTW, what is the memory usage of the application now?

**Comment by crygnus** [comment]
Total memory usage is around 622MB out of which I suspect more than 400 MB is Jenkins. Some for other OS related processes. So the application memory usage is not more than 150 MB or so.

**Comment by prasadtalasila** [comment]
The current memory usage is too high. All the more reason to check #17 for beta release.
