### ISSUE TITLE
Pub-Sub library

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#2]
We were planning to use a part of vert.x library for pub-sub. But, it seems that Google Guava collections API already has a lightweight pub-sub class. The details are available at:

https://github.com/google/guava/wiki/EventBusExplained

**Comment by crygnus** [comment]
**Google Guava** [EventBus](https://github.com/google/guava/wiki/EventBusExplained) library is used for implementing Pub-Sub design pattern in analyzers. Read more detailed discussion [here](https://github.com/prasadtalasila/PacketAnalyzer/wiki/Analyzer-Architecture#pub-sub).
