### ISSUE TITLE
Errors in packet identifiers

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#26]
The packet identifiers are not incrementing by one. There must be a synchronization issue in the packet identifier increment code.

**Comment by crygnus** [comment]
PacketIds are now incrementing by one. Changed the id generation strategy from GenerationType.AUTO to GenerationType.TABLE for the entity PacketIdEntity. See the code change [here](https://github.com/prasadtalasila/PacketAnalyzer/commit/8dabf44219fa3e4334eb9a97779e28dec5e828b1#diff-a52b9c738b2bdb311776be6f9ed5f700R29).
