### ISSUE TITLE
Integration of ELK Stack for UI

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#28]
The elk stack has logstash, elastic search and kibana. These three components can take MySQL storage from the packetanalyzer and perform most of the work related to packet exploration. The logstash and elastic search can perform the MVC job on the server-side. The kibana can help perform the data exploration job on the client-side.

**Comment by crygnus** [comment]
I presume this one is to be carried forward by the new student. Do we need to change the assignee for this one (and similarly others)?

**Comment by prasadtalasila** [comment]
Not a priority right now.
