### ISSUE TITLE
CI-DI possibilities

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#3]
Two continuous integration + deployment approaches seem good.
1) GitHub --> CodeShip (for Jenkins) --> Heroku
http://blog.codeship.com/github-heroku-rails-deployment/
One hiccup: They support only Postgres, not MySQL; but the transition should be smooth
https://devcenter.heroku.com/articles/heroku-mysql

2) GitHub --> OpenShift
has built-in Jenkins and MySQL support
http://blog.anthavio.net/2014/01/deploy-to-openshift-from-github.html
https://developers.openshift.com/en/managing-continuous-integration.html

**Comment by crygnus** [comment]
Already discussed in the this issue - 

https://github.com/prasadtalasila/PacketAnalyzer/issues/5
