### ISSUE TITLE
Potential library for p4 parse graph editor

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#30]
**Summary:** Order of potential candidates is:
1) http://gojs.net/latest/index.html
2) cytoscape.js
3) raphael.js

The director graph editor module of the d3.js library seems like an apt candidate for implementation of this feature. see the [demo](http://bl.ocks.org/rkirsling/5001347). The latest edition of [jsNetworkX library](http://jsnetworkx.org/) uses the graph editor of d3.js to create graphs dynamically.

Another simple library for graph editing is [arbor.js](http://arborjs.org/).

Other possibility is to directly use a webGL javascript library such as [three.js](http://threejs.org/) or [processing.js](http://processingjs.org/) to create graph editor from scratch. In this area, even [paper.js](http://paperjs.org/) seems promising.

References:
summary http://stackoverflow.com/questions/7034/graph-visualization-library-in-javascript  
creating graphs in processing http://processingjs.nihongoresources.com/graphs/  
A js to render dot files http://www.ryandesign.com/canviz/  
another graphviz renderer https://mdaines.github.io/viz.js/  
http://www.graphdracula.net/  
http://philogb.github.io/jit/demos.html  
A comparison http://socialcompare.com/en/comparison/javascript-graphs-and-charts-libraries  
Another comparison https://www.smashingmagazine.com/2012/02/web-drawing-throwdown-paper-processing-raphael/

**Comment by sukantoguha** [comment]
Looking into it.

**Comment by prasadtalasila** [comment]
To be implemented later.
