### ISSUE TITLE
UI not showing UDP data

### ISSUE THREAD

**Issue by crygnus** [prasadtalasila/BITS-Darshini#31]
Tested on a pcap file containing UDP packets. Custom analyzer for UDP has been added to [latest backend commit](https://github.com/prasadtalasila/PacketAnalyzer/commit/2eec0adf9977416bfb86f7124a5dd6fba78ff324).
Run the experiment and see that UDP data is available in elasticsearch (URL - http://localhost:9200/YOUR_INDEX_NAME/udp/_search?pretty). But corresponding data is not showing up on analysis page.

**Comment by sukantoguha** [comment]
Done.
