### ISSUE TITLE
Incorrect validation algorithm for Protocol graph validation in UI

### ISSUE THREAD

**Issue by crygnus** [prasadtalasila/BITS-Darshini#32]
Validation algorithm is rejecting a perfectly valid (from the point of view of backend, and the fact that such protocol graph successfully ran an experiment) thus keeping the Analyzer button disabled. Please check and report.

@sukantoguha  Please refer to the same pcap file I have sent over the email to perform the experiment.

**Comment by crygnus** [comment]
Please give the link for correction commit and close this issue.

**Comment by sukantoguha** [comment]
https://github.com/prasadtalasila/PacketAnalyzer/commit/9932917b855e853f323d1382c0cebcf212e2a880
