### ISSUE TITLE
Support for new protocols

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#36]
The following protocols need to be added to the packet analyzer

ICMPv4, ICMPv6, HTTP, MPLS, ARP, RARP, DHCP, VLAN, WiFi (802.11)

**Comment by crygnus** [comment]
Adding support for data link layer protocols is little tricky as of now. It would require two changes - 
1. Creating the analyzers and supporting files with - [P4toJava library](https://github.com/prasadtalasila/P4toJava)
2. Adding the new DLT for it in [here](https://github.com/prasadtalasila/BITS-Darshini/blob/master/src/main/java/in/ac/bits/protocolanalyzer/analyzer/PcapAnalyzer.java#L93)

Corresponding DLT can be found out by looking at [Pcap4j documentation](http://www.javadoc.io/doc/org.pcap4j/pcap4j/1.6.5). Look for DataLinkType class in package org.pcap4j.packet.namednumber

**Comment by prasadtalasila** [comment]
Not a priority right now.
