### ISSUE TITLE
Threading issue in elastic search 

### ISSUE THREAD

**Issue by anurag-rai** [prasadtalasila/BITS-Darshini#40]
Catalina Log shows:
```
org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads

SEVERE: The web application [/protocolanalyzer] appears to have started a thread named
[elasticsearch[transport-node][http_server_worker][T#12]{New I/O worker #12}] but 
has failed to stop it. This is very likely to create a memory leak.
```

This is **currently** not causing any major problem, but it would be better if resolved for future development and performance enhancement.

**Comment by prasadtalasila** [comment]
This is due to Elastic Search. The only solution is to upgrade to the latest version of Elastic Search. Dependecy upgrades are being tracked through #48.
