### ISSUE TITLE
Web-app fails to load without internet connection

### ISSUE THREAD

**Issue by anurag-rai** [prasadtalasila/BITS-Darshini#41]
It seems like some part of the front-end relies on the internet, as when the application is tried to be deployed locally without internet, it fails.

**Comment by SebastinSanty** [comment]
jquery-ui is taken from CDN. I might migrate to materialize from jquery-ui, in the process of building the new UI. So I think this issue can be kept at standstill for now.

**Comment by anurag-rai** [comment]
@SebastinSanty Can this be given a higher priority in your schedule? This is really causing a lot of problems for my branch. Or is it the case that it can only be fixed with the merge from material branch?

**Comment by SebastinSanty** [comment]
@anurag-rai It will be fixed in the material branch, which is at the verge of completion. Will be merged in a day or two.

**Comment by SebastinSanty** [comment]
Resolved as there are no longer libraries which use CDNs except icons.
