### ISSUE TITLE
Secure access to Elastic Search

### ISSUE THREAD

**Issue by anurag-rai** [prasadtalasila/BITS-Darshini#42]

**Comment by prasadtalasila** [comment]
There are some interesting pointers on the [References](https://github.com/prasadtalasila/BITS-Darshini/wiki/Interesting-References) page. Broadly speaking we can either take the approach of secure API gateway like Kong or use a plug-in to secure the Elastic Search.

**Comment by prasadtalasila** [comment]
Not a priority right now.
