### ISSUE TITLE
browser js dependency management

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#44]
The code quality assessment done by [code climate](https://codeclimate.com/github/prasadtalasila/BITS-Darshini) is very revealing. Without any excludes specified in .codeclimate.yml, the project code quality assessment came to be 0.2 / 4.0. After excluding the external client-side libraries listed below, the code quality assessment jumped to 3.6 / 4.0.

- src/main/webapp/WEB-INF/js/backbone.localstorage/
- src/main/webapp/WEB-INF/js/backbone/
- src/main/webapp/WEB-INF/js/bootstrap/
- src/main/webapp/WEB-INF/js/cookie/
- src/main/webapp/WEB-INF/js/interact/
- src/main/webapp/WEB-INF/js/jquery/dist/
- src/main/webapp/WEB-INF/js/src-noconflict/
- src/main/webapp/WEB-INF/js/underscore/
- src/main/webapp/WEB-INF/js/w2ui/
- src/main/webapp/WEB-INF/js/wysiwyg/
- src/main/webapp/WEB-INF/css/bootstrap/
- src/main/webapp/WEB-INF/css/dragula/
- src/main/webapp/WEB-INF/css/w2ui/

If there are any unused dependencies in the above list, we need to remove them. The following dependencies are certainly not needed.

- src/main/webapp/WEB-INF/css/w2ui/
- src/main/webapp/WEB-INF/js/w2ui/
- src/main/webapp/WEB-INF/js/wysiwyg/

Are we using **jquery** in any meaningful way? If not, we can remove that too.    

At present, the **ACE** code editor is in a non-obvious folder named _src-nonconflict_. If we can rename the folder to ace or c9, that would be more context-specific.

**Comment by SebastinSanty** [comment]
jquery is being used by jquery-ui. I'll change the name of ace editor dependencies folder. I'll clean up the files which aren't necessary, during the process of making a new UI as mentioned in the last review meeting.

**Comment by SebastinSanty** [comment]
Now dependencies are being managed by npm.
Pending: ace-editor folder has to be renamed.

**Comment by prasadtalasila** [comment]
Problem mostly fixed.
