### ISSUE TITLE
Correction to protocol.info table in elasticsearch

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#59]
The **Load Experiment** webpage would require to fetch entries of _protocol.info_ and show the same to the logged in user. In the same view, when a user selects an experiment, the user should be able to view the completed analysis of that experiment. Such a capability would require linking of experimental description with the corresponding analysis. One way to achieve such a linking would be to correctly insert entries in _protocol.info_table_.

At present, the protocol.info table is used to store the description of an experiment. This json entry is created by the **Experiment Description** page. At present, the `id` entry is _null_, but should actually be holding the _protocol_session_sessionID_. With a correct  _protocol_session_sessionID_, **Load Experiment** webpage can correctly specify the analysis index for the **Analysis View** page.

**Comment by SebastinSanty** [comment]
This issue has been resolved in the referenced commits.
