### ISSUE TITLE
New delegation table in ElasticSearch

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#60]
The collaboration of experimenters is a desirable feature in BITS Darshini. For us collaboration means one experimenter making the experimental description and the corresponding completed analysis available to another experimenter. In order to make this possible, we need the following table in elastic search.

```
protocol.delegate
-----------------------------------------------
| experimenter | ExperimentID | Collaborators |
-----------------------------------------------
```
ExperimentID is same as _protocol_session_sessionID_ entry of protocol.info table. It is also same as the index created for each analysis.

**Comment by SebastinSanty** [comment]
Has been resolved by the above mentioned commit.
