### ISSUE TITLE
Implementation of security framework

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#7]
The security framework as outlined in the wiki page https://github.com/prasadtalasila/PacketAnalyzer/wiki/Security-Model needs to be integrated into the product.

**Comment by prasadtalasila** [comment]
Because of time constraints, we will move this to beta release.

**Comment by crygnus** [comment]
Regarding the security policy for analyzers, a similar issue (or a parent issue of this one) is already being tracked [here](https://github.com/prasadtalasila/BITS-Darshini/issues/38). Essentially, pluginable analyzers approach will enable us to enforce suitable security policies.
User security layering model is a tricky problem. Do we have a design/idea for that on the table?

**Comment by prasadtalasila** [comment]
true
