### ISSUE TITLE
Java custom plug-ins

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#8]
Packet analyzer modified to allow custom plug-ins in a dedicated directory. The plug-in comes as a signed jar file generated from a Java template file.

**Comment by crygnus** [comment]
Java template file approach is discouraged. The feature regarding custom analyzers is tracked in a [different issue](https://github.com/prasadtalasila/PacketAnalyzer/issues/9). Please clarify more or close this issue.
