### ISSUE TITLE
Wireshark like custom plug-ins

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#9]
Simple custom plug-in along the lines of Wireshark Generic Dissector (WSGD). The documentation for WSGD is available at is, http://wsgd.free.fr/

**Comment by crygnus** [comment]
Custom analyzer generation is added as a feature to this software. To utilize this feature check out [this repository](https://github.com/crygnus/P4toJava).

Closing this issue because of its generic nature. Feel free to open a specific issue regarding this feature.
