### ISSUE TITLE
Loading analysis view

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#91]
At present, the P4 validation view waits for the analysis to be complete before it loads the analysis view. We need to load the analysis view immediately after user clicks on the analyze button.

**Comment by SebastinSanty** [comment]
This might not be a problem of client side, because as soon as it receives a success on its request to backend, it directs to analysis page. This snippet suggests that:

https://github.com/prasadtalasila/BITS-Darshini/blob/master/src/main/webapp/WEB-INF/js/views/config-playground-view.js#L26-L39

**Comment by prasadtalasila** [comment]
Is the [packetCount](https://github.com/prasadtalasila/BITS-Darshini/blob/master/src/main/webapp/WEB-INF/js/views/config-playground-view.js#L37) being used in any meaningful way on the client side?

@anurag-rai extracting packetReadCount from pcap file in [Session.java](https://github.com/prasadtalasila/BITS-Darshini/blob/master/src/main/java/in/ac/bits/protocolanalyzer/analyzer/Session.java#L98) will only happen after the entire pcap file is read. This event happens typically towards the end of analysis. If the front-end does not require the packet count, we can skip the same and will have a responsive UI.

**Comment by prasadtalasila** [comment]
Not a priority right now.
